

@startuml 

title: Organizer creates events and receives reports

 
actor "Organizer" as organizer
participant "__:MainController__" as mainctrl
participant "__:Event_Catalog__" as eventCat
participant "__:Event__" as event
participant "__:Event_TDG__" as eventtdg
collections "Events" as events
participant "__:Report__" as report
collections "Reports" as reports

organizer --> mainctrl: createEvent(name, startDate, endDate, startTime, endTime)
mainctrl --> eventCat : createEvent(name, startDate, endDate, startTime, endTime)
eventCat --> event **: createEvent(name, startDate, endDate, startTime, endTime)
event --> eventCat : return e:event
event--> eventtdg : addevent(name, startDate, endDate, startTime, endTime)
eventCat --> sees_events: addEvent(E)
events --> mainctrl: confirmation
mainctrl --> organizer: confirmation

organizer --> mainctrl: finishEvent(e)
mainctrl --> report**: createReport(e, organizer)
report --> mainctrl: return r:report
mainctrl --> reports: addReport(r)
reports --> mainctrl: confirmation
mainctrl--> organizer: confirmation






@enduml 