@startuml
title: Event Chatroom Sequence Diagram 

actor Attendee
participant "__Main_Controller__" as main
participant "__Event_Catalog__" as eventCatalog
participant "__:Event__" as event
participant "__:Engagement_Manager__" as em
participant "__:Participant_Catalog__" as pc
collections "__:Participant__" as participant
participant "__:Chatroom__" as chatroom


note left : a Participant is an association class \n between a user and an event,but it's contained \nin participan_registry , which is an attribute of Event. \n We have to change this. \nHere I will consider a participant to be a user. 

Attendee -> main : joinChatroom(eid :int)
main -> eventCatalog : joinChatroom(user:User, eid : Int)
eventCatalog -> event : joinChatroom()
event -> pc : isParticipant(participant:User)
pc -> participant : p: find(participant: User)
participant --> pc : confirm is Participant 
em --> event : Confirmation
event--> eventCatalog : Confirmation
eventCatalog --> main : Confirmation
Attendee ->main : chat(user: User, message:String)
main -> eventCatalog: sendChatMessahe(user: User, message: String)
eventCatalog-> event : chat(user: User, message: String)
event->em: chat(user: User, message:String)
em-> chatroom : sendMessage(user: User, message: String)
em --> event : Confirmation
event--> eventCatalog : Confirmation
eventCatalog --> main : Confirmation


@enduml