@startuml

title: Browse Events

actor Attendee
participant "__:Main_Controller__" as mc
participant "__:Event_Catalog__" as ec
collections "__:Event__" as event
participant "__:FilteringController" as fc


== See all events ==
Attendee -> mc : seeAllEvents
mc -> ec : showAllEvents()

loop for each event
  ec -> event : showEventInGrid()
  event --> ec : render Event thumbnail in grid

end 
== Filter by category ==
Attendee -> mc : filterEvent (c : Category)
mc -> ec : showFilteredEvents()

loop for each event
  ec -> event : isCategory(c)
  event --> ec : true
  ec -> event : showEventInGrid()
  event --> ec : render Event thumbnail in grid

end 

== Filter by keyword ==
Attendee -> mc : filterEvent (keyword : String)
mc -> ec : showFilteredEvents()

loop for each event
  ec -> event : isInDescription(keyword)
  event --> ec : true
  ec -> event : showEventInGrid()
  event --> ec : render Event thumbnail in grid

end 

@enduml