@startuml
title Schedule and Location
left to right direction
actor "Organizer" as org
actor "Attendee" as attendee
 
rectangle SEES {
  usecase "Manage Event Schedule & Location" as U2
  usecase "Add Session" as U2a
  usecase "Update Session Time" as U2b
  usecase "Edit Location" as U2c
  usecase "View Schedule & Location" as U2d
}
 
org -- U2
attendee -- U2d
 
'U2 "includes" these sub-tasks:
U2 --> U2a : <<include>>
U2 --> U2b : <<include>>
U2 --> U2c : <<include>>
@enduml
